export const allItems = [
    {_id:"100",title:"All Departments"},
    {_id:"101",title:"Automotive"}, 
    {_id:"102",title:"Beauty & Personal Care"}, 
    {_id:"103",title:"Books"}, 
    {_id:"104",title:"Boy's Fashion"}, 
    {_id:"105",title:"Computers"},
    {_id:"106",title:"Deals"},
    {_id:"107",title:"Electronics"}, 
    {_id:"108",title:"Girl's Fashion"}, 
    {_id:"109",title:"Health"},
    {_id:"110",title:"Men's Fashion"},
    {_id:"111",title:"Movies & TV"},
    {_id:"112",title:"Sports"},
    {_id:"113",title:"Sneakers"},
    {_id:"114",title:"Toys"},
    {_id:"115",title:"Tools"},
    {_id:"116",title:"Video Games"},
    {_id:"117",title:"Women's Fashion"},
]